# https://www.tutorialspoint.com/makefile/makefile_example.htm
# https://opensource.com/article/18/8/what-how-makefile

# Define required macros here
SHELL = /bin/sh

create-folders:
	@echo "Create folders"
	cd app && mkdir -p chop output load rubberband split
